FROM golang:latest as builder
WORKDIR /go/src/github.com/jenkins-zh/mirror-proxy

COPY . .
RUN make linux

FROM alpine:3.3
LABEL maintainer="Rick <rick@jenkins-zh.cn>"
LABEL Description="This is the Jenkins update center mirror proxy"

USER root
RUN sed -i 's|dl-cdn.alpinelinux.org|mirrors.aliyun.com|g' /etc/apk/repositories
RUN apk add --no-cache ca-certificates curl

COPY --from=builder /go/src/github.com/jenkins-zh/mirror-proxy/bin/linux/mirror-proxy .

EXPOSE 7070

ENTRYPOINT ["./mirror-proxy"]
