FROM golang:latest as builder

LABEL maintainer="Rick <rick@jenkins-zh.cn>"

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

FROM alpine:3.3

USER root

RUN sed -i 's|dl-cdn.alpinelinux.org|mirrors.aliyun.com|g' /etc/apk/repositories
RUN apk add --no-cache ca-certificates curl

COPY --from=builder bin/linux/mirror-proxy .
RUN chmod u+x mirror-proxy

COPY config/.mirror-proxy.yaml /root/.mirror-proxy.yaml

ENTRYPOINT ["./mirror-proxy"]
CMD []